### ISSUE TITLE
Redundant argument in printf at Core.pm line 320

### ISSUE THREAD

**Issue by ob7** [domm/App-TimeTracker#16]
I've had to change:
``` $self->beautify_seconds( delete $data->{'_total'} ), ''```
to:
``` $self->beautify_seconds( delete $data->{'_total'} )```
To make tracker report --this day do so without saying:
```Redundant argument in printf at /perl5/lib/perl5/App/TimeTracker/Command/Core.pm line 320.```
Every other line in the print out.
So I'm not sure what the extra argument is for, but it prints report just fine with no errors when I remove the last argument being passed to print from the report command in Core.

**Comment by domm** [comment]
Thanks!

I've fixed this by adapting the printf-fromat depending on whether the user wants to output some detail or not
