### ISSUE TITLE
Dealing with projects with same path names

### ISSUE THREAD

**Issue by zmughal** [domm/App-TimeTracker#57]
I have `.tracker.json` configuration files named under paths, e.g.,:

```
# For org1
org1/.tracker.json         # { "project": "org1" }
org1/devops/.tracker.json  # { "project": "devops" }

# For org2
org2/.tracker.json         # { "project": "org2" }
org2/devops/.tracker.json  # { "project": "devops" }
```

This means that when `projects.json` is created it can not handle duplicate
project names:

```
{
	"devops" : "[ one of the projects and not the other ]"
}
```

So I thought, maybe I can be explicit about the full project name by making the
following changes to the the configurations:

```diff
-org1/devops/.tracker.json  # { "project": "devops" }
+org1/devops/.tracker.json  # { "project": "org1/devops" }

-org2/devops/.tracker.json  # { "project": "devops" }
+org2/devops/.tracker.json  # { "project": "org2/devops" }
```

but this does not work because the way the current config merging code works is
that it uses the last component of the path instead of the `project` key of the
configuration file: <https://github.com/domm/App-TimeTracker/blob/3.008/lib/App/TimeTracker/Proto.pm#L194>

I can work around this by:

1. generating the `.tracker.json` myself
2. adding it to `projects.json` manually
3. always using the `--project` option to specify the name

The fix that I would recommend is:

1. Allow for the `init` command to take an optional project name to use instead
   of the default.
2. When loading the configs in `.tracker.json`, look for the first file that
   sets the `project` key and use that to set the `project` attribute.

Would you be open to these changes?

**Comment by zmughal** [comment]
I have implemented the above suggestions on branch `project-attr-from-file` <https://github.com/domm/App-TimeTracker/compare/master...zmughal:project-attr-from-file> on top of the PR <https://github.com/domm/App-TimeTracker/pull/58>.

**Comment by domm** [comment]
Hey!

I was actually having the same problem (with two projects named 'infrastructure'), so i very much appreciate your patch. I'm currently on holidays, so I will most likely only get to review your patch next week. (And I have some other experimental stuff in a branch which I haven't released yet...)

So thanks a lot, but please be patient a bit :-)

Greetings,
domm

**Comment by zmughal** [comment]
I believe I have the code in a working state now with tests. I've been using it this whole time. Should I open a pull request with everything?

**Comment by domm** [comment]
Thanks for your patches, I've merged them now and just pushed a new release to CPAN. Please give it a try!
